# Generated by Django 4.1.3 on 2022-12-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_img_snack_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='time',
        ),
    ]
